### ISSUE TITLE
Unable to send emails via smtp-relay.gmail.com (EOF ERROR)

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [hrfee/jfa-go#141]
I am unable to send emails. I get an EOF error.

**To Reproduce**

1) Set up email with:
```
SMTP (Email)
Username: No Username (As google smtp-relay does IP auth)
Encryption Method: STARTTLS
Server address: smtp-relay.gmail.com
Port: 587
Password: No Password (As google smtp-relay does IP auth)
```
2) Send email and see error

What to do to reproduce the problem.

**Logs**

`[ERROR] 00:42:51 api.go:998: Failed to send to xxxxxxxxx@gmail.com: EOF`

**Configuration**

```
SMTP (Email)
Username: No Username (As google smtp-relay does IP auth)
Encryption Method: STARTTLS
Server address: smtp-relay.gmail.com
Port: 587
Password: No Password (As google smtp-relay does IP auth)
```
**Platform/Version**

Linux
Version 0.3.8
Commit 5b319d6

Include the platform jfa-go is running on (e.g Windows, Linux, Docker), the version (first line of output by `jfa-go` or Settings>About in web UI), and if necessary the browser version and platform.

**Comment by SteveGBuck** [comment]
Just to echo I'm getting exactly the same issue.

And confirm that using smtp.gmail.com instead with app specific password works as an interim solution but sends all email from my actual email address rather than the from address I use in the config.

**Comment by hrfee** [comment]
@SteveGBuck i'm setting up a trial of Google Workspace so i can try the smtp-relay thing myself and try to get this fixed.

**Comment by SteveGBuck** [comment]
Great thanks, happy to test here too.  Fantastic work BTW!

**Comment by hrfee** [comment]
I think the issue is the server hostname sent when connecting, the SMTP library I was using sends "localhost" by default, and to be able to change that would stop SSL/TLS encryption from working. I've switched to a new library in d560df5, and added an option called "HELLO Hostname" in Settings > SMTP when Advanced settings is enabled. Set this to the domain name/external IP of the server running jfa-go. My trial of Google workspace has expired, so I can't test this myself right now.
