### ISSUE TITLE
JFA sends 11 emails for one password reset request

### ISSUE THREAD

**Issue by lucasblack29** [hrfee/jfa-go#171]
As the title indicates, JFA seems to send out 11 emails for one password request to the user's email. I'm currently using 0.3.9 on Linux

**Comment by hrfee** [comment]
Sorry for the late reply, would you be able to send the logs from jfa-go with debug mode on when this occurs? I can't reproduce this myself so hopefully that'll give more insight.

**Comment by hrfee** [comment]
@kimboslice99 I've known logs have been an issue on Windows for a while, I have another system I can test on now so hopefully I can get those fixed soon. I have a completely unfounded feeling the issue is caused by "restarting" jfa-go through the web UI, it kinda just destroys and reinitializes everything but in the past things its caused weird issues like this. Do you regularly use the restart button within the UI?
