### ISSUE TITLE
Support for 10.8.0

### ISSUE THREAD

**Issue by mLgz0rn** [hrfee/jfa-go#213]
Just a quick question.
Does this support 10.8.0 yet?

I'm having an issue with a user trying to create an account

`[ERROR] 21:45:23 api.go:374: pkNPhL8AQfhdrSVuLALuQ8: New user failed: Failed to set member role: HTTP 403 Forbidden, {"message": "Missing Permissions", "code": 50013}`

**Comment by hrfee** [comment]
Hi, I haven't been working on jfa-go for a while now but i'm back to try and fix issues so sorry for the delay. This is an error related to Discord rather than Jellyfin, and usually shows up when the bot's own role is not above the user it's trying to give the role. In Discord, go to Server Settings > Roles, and make sure your bot's role is above any that the other users might have.

**Comment by mLgz0rn** [comment]
> Hi, I haven't been working on jfa-go for a while now but i'm back to try and fix issues so sorry for the delay. This is an error related to Discord rather than Jellyfin, and usually shows up when the bot's own role is not above the user it's trying to give the role. In Discord, go to Server Settings > Roles, and make sure your bot's role is above any that the other users might have.

No problem at all! I thought you would be busy since you didn't reply :D 

Ahh I see.
The role was all they way at the buttom, gonna test if it works

**Comment by mLgz0rn** [comment]
It works!

Thank you
