### ISSUE TITLE
NO LONGER WORKS WITH JELLYFIN. NEEDS WORK TO AUTHENTICATE OVER JELLYFIN 10.7

### ISSUE THREAD

**Issue by cmileto** [hrfee/jfa-go#247]
Heads up if you are trying to install
seems to work. pls ignore. I have installed successfully

**Comment by stickus** [comment]
I'm currently using this with 10.8.9 right now and it works great. What kind of errors are you seeing in your log file?

**Comment by itssasanka** [comment]
I found the answer to this problem - I am running a native installation of Jellyfin and the container version of `jfa-go`. While `http://0.0.0.0:8096` worked on the setup page to connect to my jellyfin instance, the loopback quite didn't work as expected after finishing all the setup steps and immediately crashed the jfaGo container - I had to use my local IP of the machine (`192.168.172.11`) instead of `0.0.0.0` and the crash went away.
