### ISSUE TITLE
NEW RELEASES

### ISSUE THREAD

**Issue by kuesttman** [hrfee/jfa-go#252]
Why are there no more releases since January last year?
The JFA-Go code has been quite a thing since the last published version. I'd like to test these updates with docker, but I can't compile a docker image from code.

Would it be possible to release a new version ready to use and test?

**Comment by hrfee** [comment]
stable hasn't been updated since there haven't been any big features or changes added since I didn't do much work on it in the last year, but the `hrfee/jfa-go:unstable` tag is available for the changes I have made. Someone else is working on a PR with new features and I plan on adding a few more things too, at which point I will release a 0.4.1.

**Comment by aniel300** [comment]
thank u

**Comment by cmileto** [comment]
awesome
