### ISSUE TITLE
[Feature Request] Invite-specific User Default

### ISSUE THREAD

**Issue by JcfeJohn** [hrfee/jfa-go#6]
I'm sorry for opening another feature request after my previous one.

As the title says, possibility to set a **New User Defaults** to specific invite.

By default it will use the New User Defaults in settings.

-----

Also, I'll include this here. There seems to be a bug in **User creation** notification. Ticking it shows this in logs:
```
Bug 1

[DEBUG] 15:13:52 api.go:526: qrMiurBYiFPgTN7Mggtw3H: Set "notify-creation" to false for XXXX@email.com
```

Sometimes ticking **User creation** gives this:
```
Bug 2

[DEBUG] 15:15:50 api.go:487: qrMiurBYiFPgTN7Mggtw3H: Notification settings change requested
[DEBUG] 15:15:50 api.go:521: qrMiurBYiFPgTN7Mggtw3H: Set "notify-expiry" to false for XXXXX
[DEBUG] 15:15:50 api.go:526: qrMiurBYiFPgTN7Mggtw3H: Set "notify-creation" to false for XXXXX
```

To reproduce Bug 2:
Turn on **Expiry** first then after that turn on **User creation**

**Comment by hrfee** [comment]
It's fine, I'm been enjoying having something to work on, seems like no one else is creating issues on this like they did for the python version. I'll work on the feature, I was thinking of doing something like user profiles where multiple templates can be defined and chosen from so it'll fit perfectly.

As for your issues, it looks like the problem is that its doing the opposite of what you want (ticking it is setting is to false), right?

**Comment by JcfeJohn** [comment]
Oh, multiple templates would be great!

Yes, it is doing the opposite. Turning it on sets it to false

**Comment by hrfee** [comment]
ok, fixed the buttons in 49b056f, they also weren't displaying there actual value correctly after a refresh.

**Comment by JcfeJohn** [comment]
There is also a visual bug in Settings > Account Deletion > Email subject

I think it doesn't save as well. Upon saving, it is blank

**Comment by hrfee** [comment]
Ah yeah, that actually applies to all of the email subject fields, as the
default values are only added to your config file on first run. For now
I'll just fill in the values when the config is loaded.

**Comment by hrfee** [comment]
i've just about finished implementing this in the form of profiles, which are named and store policy and homescreen layout. On first run it'll backup and migrate your older files into a profile called "Default". You can create more in Settings > User Profiles. These can be set per invite on creation, and the profile for an invite can be changed later in its dropdown. The accounts window also lets you change settings for users with them.

This one took a little longer because I decided i wanted to rewrite the web UI in typescript first, and I also made a couple UI changes. The only thing missing (i think) is setting the default profile to use, but i'll add that soon. [here's](https://nextcloud.hrfee.pw/s/tPzmCTjxTDatePG) a build.

**Comment by JcfeJohn** [comment]
I just tested it out and it looks great!

**Comment by hrfee** [comment]
This feature and some more stuff is now part of the 0.2.0 release.
