### ISSUE TITLE
Config file does not get updated when features are added

### ISSUE THREAD

**Issue by Spiritreader** [hrfee/jfa-go#7]
**The issue**

When a new feature is added and you try to enable it in the web UI, the settings will not save.
This seems to be because config files from an older version do not have the required fields present and they aren't appended automatically.

A workaround is to delete redo the entire configuration with the setup page as this generates an entirely new config file with all the options present, but it's really not that obvious to spot if you're not a poweruser/dev who knows where to look.

I remember pondering about this problem when I was working on my own go application config file. I oped to use json and a struct for the config and just json serialized/deserialized the entire struct. Had the advantage that missing fields would just get added with a default value.
Maybe something similar could be applicable here: The entire config with all fields is saved with default values, regardless of which fields were present during load.

Since you're using a text based file and I haven't had the chance to look at the exact implementation (I remember it was maybe key-value based), I can't tell if this approach would be effective for you also.

**To Reproduce**

Use an older config file, for example pre-ombi integration and try to enable ombi integration with the web interface.

**Platform/Version**
- Dockerized
- Version 0.1.9
- Commit 4e86288

**Comment by hrfee** [comment]
Fixed in 6b252157682d56c6e9e61520091d8ba01227ed19. Not sure how I hadn't noticed this before, thanks. 

My implementation of the config is a bit of a mess. I'm using the [ini](https://pkg.go.dev/github.com/go-ini/ini) library for reading and writing changes to the config file, but every field along with its description, datatype and options are defined in `config-base.json` so that the web ui can display settings properly. On compile, a python script converts this into an ini file. I think yaml or toml might have been a better choice, but i wanted compatibility with jellyfin-accounts so i stuck with ini.
