### ISSUE TITLE
[FEATURE REQUEST] Add support to notify via Telegram

### ISSUE THREAD

**Issue by xiNeRoar** [hrfee/jfa-go#94]
The notification channel right now only support email. Is is possible to add telegram as another way to notify my users?

**Comment by hrfee** [comment]
I've started work on this and it doesn't look as difficult as I thought. Since the Telegram bot API requires the user to interact with the bot first, The user will first have to send a PIN given on the sign up page to allow contact and also verify their account. From there jfa-go can just send the current plain text versions of emails. Should have it done within a few days.
