### ISSUE TITLE
[FEATURE REQUEST] Discord support

### ISSUE THREAD

**Issue by ddurdle** [hrfee/jfa-go#95]
Since I saw Telegram support, Discord support would be nice.

**Comment by hrfee** [comment]
I was thinking of this too, since most of the code can be shared.

**Comment by atmos-o** [comment]
I actually came to request something like this. Having most if not all notifications done through a Discord bot, DM'ing people with things like invite link & other stuff rather than email would be great. Having an admin setuo channels where notifications can be sent would be great. 

jfa-go don't need to have their own bot up either, there are very simple self-hosted Discord bots people can throw up themselves. I already have my own instance of "Red-Bot" running.

Another big feature I also had in mind was auto creating invite links when a user requests it using a command in discord. 
That way you can take yourself out of the equation all together. Can restrict this command usage only to specific roles like "Nitro Booster" to incentivise users to boost. And when they lose that role jfa-go disables their account until they get the role back and reactivate.

**Comment by hrfee** [comment]
@atmos-o I've only just started on this, i'm in the middle of exams and this seemed like a big feature so I put it off. The discord API is less confusing than I thought so this should be added by the end of the week.

> jfa-go don't need to have their own bot up either

The bot code is part of jfa-go, the person running jfa-go just needs to create a bot in the Discord developer portal and put the API key in the config.

> Another big feature I also had in mind was auto creating invite links when a user requests it using a command in discord ...

This is a great idea, but this might take a bit longer than the rest of the integration.

**Comment by atmos-o** [comment]
> The bot code is part of jfa-go 

Yeah thats true. Even easier for people as you guys have a fleshed out app already (awesome work btw)

> This is a great idea, but this might take a bit longer than the rest of the integration.

I seriosuly have been going on a wild goose chase for a while wanting to find something to allow my friends access to my library as my setup can manage it. I went looking at ways to create movie streaming site clones & projects here on Github. To easily allow friends access without micromanaging every step, to where the computer illiterate ones could manage it too. Give access to people by simply adding/removing a discord role.

This paired with the **synced/party viewing** feature could be amazing. Allow everyone to join for movie nights without making each person a account one by one and start watching together instantly. I still hope JF improves their synced party viewing gets improved though.

**Comment by hrfee** [comment]
@atmos-o @ddurdle Just merged the discord branch, most features are done (see #102 for the full list). To actually create the bot, there's a new wiki post [here](https://github.com/hrfee/jfa-go/wiki/Discord-Bot-Setup).

**Comment by atmos-o** [comment]
Doesn't seem to be working for me. Bot does not go online even when creating a new app & using a new bot. Does not respond to !start or custom command set.

**Comment by hrfee** [comment]
@atmos-o anything in the jfa-go logs about it? If there's any errors they should be in red.
